apiVersion: v1
kind: ConfigMap
metadata:
  name: tenants-config
data:
  DB_HOST: "postgres-tenants"
  DB_PORT: "5432"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "aaw-tugas-1-tenants"
  NODE_ENV: "production"
  PORT: "8003"
  AUTH_SERVICE_URL: "http://auth-service.default.svc.cluster.local:8000"