apiVersion: v1
kind: Service
metadata:
  name: tenants-service
spec:
  type: NodePort
  selector:
    app: tenants
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
      nodePort: 30003
  