apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-wishlists
spec:
  serviceName: "postgres-wishlists"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-wishlists
  template:
    metadata:
      labels:
        app: postgres-wishlists
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: wishlists-config
            - secretRef:
                name: wishlists-secret
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
