apiVersion: v1
kind: Service
metadata:
  name: wishlists-service
spec:
  type: NodePort
  selector:
    app: wishlists
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
      nodePort: 30004
  