apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      initContainers:
        - name: wait-for-db
          image: bitnami/minideb
          command: ["sh", "-c", "apt-get update && apt-get install -y netcat && until nc -z postgres-auth 5432; do echo waiting for db; sleep 2; done;"]
        - name: migrate-db
          image: matthewhjt/authentication-service:latest
          command: ["sh", "-c", "node dist/src/db/migrate.js"]
          envFrom:
            - configMapRef:
                name: auth-config
            - secretRef:
                name: auth-secret
      containers:
        - name: auth
          image: matthewhjt/authentication-service:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: auth-config
            - secretRef:
                name: auth-secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 10
