apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-config
data:
  DB_HOST: "postgres-orders"
  DB_PORT: "5432"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "aaw-tugas-1-orders"
  NODE_ENV: "production"
  PORT: "8001"
  PRODUCT_MS_URL: "http://products-service.default.svc.cluster.local:8002/api"