apiVersion: v1
kind: Service
metadata:
  name: postgres-orders
spec:
  selector:
    app: postgres-orders
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None  # Agar StatefulSet mendapatkan DNS internal yang stabil
