apiVersion: v1
kind: Secret
metadata:
  name: orders-secret
type: Opaque
data:
  DB_PASSWORD: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM= 
  JWT_SECRET: YXV0aF9tc19qd3Rfc2VjcmV0
  ADMIN_JWT_SECRET: YWRtaW5fYXV0aF9tc19qd3Rfc2VjcmV0  
  TENANT_ID: ZjA0YzJjZmYtNTdkOS00OWM3LTg4ZDktNjIxMGUwNzQ4MzM3
  ADMIN_TENANT_ID: ZjA0YzJjZmYtNTdkOS00OWM3LTg4ZDktNjIxMGUwNzQ4MzM3