apiVersion: v1
kind: ConfigMap
metadata:
  name: products-config
data:
  DB_HOST: "postgres-products"
  DB_PORT: "5432"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "aaw-tugas-1-products"
  NODE_ENV: "production"
  PORT: "8002"
  AUTH_SERVICE_URL: "http://auth-service.default.svc.cluster.local:8000"
  TENANT_SERVICE_URL: "http://tenants-service.default.svc.cluster.local:8003"