apiVersion: v1
kind: Service
metadata:
  name: products-service
spec:
  type: NodePort
  selector:
    app: products
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
      nodePort: 30002
  